### ISSUE TITLE
Calendar events not showing in realtime .

### ISSUE THREAD

**Issue by vinay13** [mattlewis92/angular-calendar#103]
I'm adding a new event from a view and after submitting . it automatically comes back to the calendar's view . But the problem is the new event is not showing at that time , it only shows after a refresh . 
I also pushed the new object to events[].
How can i achieve this showing calendar events without refreshing the view.

**Comment by mattlewis92** [comment]
This is due to a performance restriction with angular - it does not deep watch arrays. When you push to the array it doesn't create a new reference so nothing updates. The easiest way around this is to either clone the array like so:
```
this.events = [...this.events];
```

or if you want more control, use the [refresh option](https://mattlewis92.github.io/angular-calendar/docs/classes/calendarmonthviewcomponent.html#refresh). There is a test that shows how to use that [here](https://github.com/mattlewis92/angular-calendar/blob/master/test/calendarMonthView.component.spec.ts#L177-L196).

Hope that helps! 😃

**Comment by vinay13** [comment]
Thanks you so much . It works!!
