### ISSUE TITLE
Custom CalendarEventTitleFormatter Gets Some HTML Sanitized by Angular 8.1

### ISSUE THREAD

**Issue by JaxonWright** [mattlewis92/angular-calendar#1036]
**Describe the bug**

In one of the projects that I am working on, we are using Angular Font Awesome to get high-quality icons. We have a custom event title formatter to display more information on the events in the Day and Week views. Within those views' event titles, we are using FontAwesome. Recently, this stopped working because Angular now sanitizes the HTML. It seems like Angular 8.1 has gotten more aggressive in HTML sanitization.

As far as I can tell, there is no way for users of this library to tell angular to not sanitize this text. Either allowing that option to be turned on..or just doing it by default would be great.

**Minimal reproduction of the problem with instructions**

Here you can see me using an icon at the top of the page; it loads fine. When I try to include the same icon within the `day()` function of the `CustomEventTitleFormatter`, Angular decides to sanitize it. I am sure this occurs with other HTML elements, I just know that it is at least a problem with `<fa-icon>`.
https://stackblitz.com/edit/angular-foth8s

**Versions**

- `@angular/core`: 8.1.1
- `angular-calendar`: 0.27.13
- `Browser name and version`: Chrome 75.0.3770.100 on Windows 10

**Comment by mattlewis92** [comment]
The issue is caused by `fa-icon` being an angular component - everything in angular needs to be statically analysable for AoT to work, so you can't construct components by creating them with strings and setting them to the innerHtml of an element (maybe in the future with ivy this will be possible?). What you can do as a workaround is use a [custom template](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template) for the [`eventTitleTemplate`](https://github.com/mattlewis92/angular-calendar/blob/master/projects/angular-calendar/src/modules/common/calendar-event-title.component.ts) of the component. Hope that helps! 😄

**Comment by JaxonWright** [comment]
That makes sense because we did just recently switch to AoT at the same time as updating to Angular 8 from 7. I'll give that a try, thanks.

**Comment by bluefire2121** [comment]
@jaxonWright have you considered using Renderer2? It's an angular library that allows for safe DOM manipulation after AOT. It allows you to build HTML components post-render.
