### ISSUE TITLE
Drag to create events - expands too fast when hourSegment is larger than 2

### ISSUE THREAD

**Issue by notsure** [mattlewis92/angular-calendar#1037]
**Describe the bug**

Check out the demo:
https://stackblitz.com/run

I've only added the `[hourSegments]="4"` property to the html.

```
<mwl-calendar-week-view
  [viewDate]="viewDate"
  [events]="events"
  [hourSegments]="4"
  [hourSegmentTemplate]="weekViewHourSegmentTemplate"
>
</mwl-calendar-week-view>
```

Now drag an event in the preview. You will notice that by moving your mouse down the event item expands too fast. With the default hour segment of 2 the expanding speed is in the same way as the cursor hits a new hour segment. However with a greater hour segment than default, the ratio is out of synch.

I would expect to increase the event duration in the same interval, as it does with the hour segment of 2

**Minimal reproduction of the problem with instructions**

Check out the demo:
https://stackblitz.com/run

**Versions**

0.27.13

- Browser name and version:
Mac - Chrome - Version 75.0.3770.100 (Official Build) (64-bit)

**Comment by mattlewis92** [comment]
Thanks for opening an issue, the problem is caused because the code assumes that [each segment is 30 minutes](https://github.com/mattlewis92/angular-calendar/blob/master/projects/demos/app/demo-modules/drag-to-create-events/component.ts#L97). By doing `hourSegments="4"`, each segment becomes 15 minutes instead. So if you just divide by 2, then it should fix your issue: https://stackblitz.com/edit/angular-vp1el6?file=demo/component.ts Hope that helps! 😄

**Comment by notsure** [comment]
@mattlewis92  Thanks for this quick fix!
