### ISSUE TITLE
Day event cannot be sorted by event title (Reopened)

### ISSUE THREAD

**Issue by disappointman** [mattlewis92/angular-calendar#1041]
**Is your feature request related to a problem? Please describe**
I cannot sort the day events by event name.

**Describe the solution you'd like**
A feature that could sort the day events by its' event name or anything other than start time would be nice.

**Describe your use case for implementing this feature**
I want to sort the day event using the event name.

**Additional context**
Attached image shows how the events are sorted by time, I would like to sort it by event name. 
![image](https://user-images.githubusercontent.com/29259401/61507686-4af53900-aa19-11e9-8e1b-c93d6bc7beef.png)

**Comment by JaxonWright** [comment]
Are you sure sorting the event array by name doesn't solve this issue?

**Comment by mattlewis92** [comment]
This is actually by design as events are sorted by start date to be placed optimally on the view i.e. so if you have 2 events that fit in the same column it will place them above each other, rather than in a new column:

<img width="246" alt="Screenshot 2019-07-20 at 18 19 19" src="https://user-images.githubusercontent.com/6425649/61581813-f5a15080-ab1a-11e9-9cc0-3a9d64b6ec16.png">

But if you want them sorted alphabetically then you can override the day view function to sort them alphabetically and not stack them. I put together an example of how to do that here: https://stackblitz.com/edit/angular-rctdpu-f1jqem?file=demo/component.ts

Hope that helps! 😄
