### ISSUE TITLE
Event after calendar load finished

### ISSUE THREAD

**Issue by zolee** [mattlewis92/angular-calendar#1085]
**Is your feature request related to a problem? Please describe**

I would like to scroll the calendar to start at 7. a.m. after the embedded component has been fully loaded. My problem is that there is no any event can be used to tell if the calendar load finished or not.

**Describe the solution you'd like**

Maybe it can be solved by exposing the `AfterViewInit` lifecycle hook as an `@Output`.

**Describe your use case for implementing this feature**

Provide  some event after we can safely access the component DOM when the component load finished.

**Additional context**

**Comment by mattlewis92** [comment]
It's a bit hacky, but you can use the `beforeViewRender` output with a setTimeout inside to get this behaviour: https://stackblitz.com/edit/angular-vtmdof?file=demo/component.ts

If I implemented it in the calendar itself, that's probably how it would be done, so I think it's cleaner to just keep it in userland rather than adding a new option. Let me know if that works for you 😄
