### ISSUE TITLE
Ability to show resources in week-view

### ISSUE THREAD

**Issue by TimexSinclair** [mattlewis92/angular-calendar#1125]
**Is your feature request related to a problem? Please describe**

The day-view is able to show resources, but the week-view cannot show resources for each day.

**Describe the solution you'd like**

It would be great if resources' names can be shown at the top of each day's column, as it's done in day-view (see Jane Doe and John Smith day-view example [here](https://mattlewis92.github.io/angular-calendar/#/day-view-scheduler)).

**Describe your use case for implementing this feature**

I need to show more than one calendar at the time and the resources concept works wonderfully for that. It's great that the day-view has the ability to work that way and it would be greater if week-view did that too! 

**Additional context**

Keep up your amazing work, Matt!

**Comment by mattlewis92** [comment]
Hey there, I'm not really too sure how this would work on the week view as each column is already used for the day, so I'm not too sure how each users events would be able to be positioned within each column without everything being crammed in and unreadable. Do you have any idea of how to solve this?

**Comment by TimexSinclair** [comment]
Hey Matt, each week-view column should continue to be used for the day, as is. However, each of those days would be like the day shown in the Jane and John example:

![image](https://user-images.githubusercontent.com/38543688/68881693-5f59f180-06ec-11ea-8707-6f70dff3e08b.png)

Instead of the (implicit) one-resource day we have now on each the of the week-view:

![image](https://user-images.githubusercontent.com/38543688/68882071-3ab24980-06ed-11ea-81fd-5cd93168082b.png)

Honestly, I don't see it being too crammed, it would depend only on how many resources you show at the same time. But with two or three resources it would work nicely.

**Comment by Kherat** [comment]
Hi,
I think we are on the same side, so I will add my question here
Can we add staff resource to the calendar as attachment image?
![Screenshot_2019-11-14 Angular Animations demo](https://user-images.githubusercontent.com/47124139/68897224-b89a4300-0735-11ea-8442-85a261866bfc.png)

**Comment by mattlewis92** [comment]
I think for these use cases, you're better off building separate components as they deviate too far from the ones provided here out of the box. This was actually one of the reasons why the [utils](https://github.com/mattlewis92/calendar-utils), [drag and drop](https://github.com/mattlewis92/angular-draggable-droppable), and [resizable](https://github.com/mattlewis92/angular-resizable-element) code are all in separate packages, so you can [build additional views](https://github.com/mattlewis92/angular-calendar#the-month-week-or-day-view-doesnt-meet-my-project-requirements-but-the-other-views-do) that suit your app's specific needs.

**Comment by FrankL-git** [comment]
I used another approach to solve the problem: The day columns are left untouched but the events widths are halved and by using the left property of the WeekViewTimeEvent John's events are in the left half of the day column and Jane's in the right half.
I "merged" the two WeekViews one would get using John's events resp. Jane's events only.
In detail:  
In the beforeViewRenderEvent create one WeekView wv_john for the events belonging to John and one wv_jane for Jane's events. You get the values for the width and left property of the WeekView.hourColumns.events if only John's resp. Jane's events would be displayed. 
For each of John's events in the WeekView to be rendered (= argument of the function waiting on beforeViewRenderEvent):
width = 0.5 * width of corresponding event in wv_john
left = 0.5 * left of corresponding event in wv_john
and for each of Jane's events:
width = 0.5 * width of corresponding event in wv_jane
left = 50 + 0.5 * left of corresponding event in wv_john

How to do this for n instead of 2 users is obvious.
Problems: 
The names of John and Jane are not displayed on top of the day columns (I use specific colors for John's and Jane's events).
During dragging and resizing of events the view is displayed as it would be without the manipulations above - but after drag's and resize's end everything looks fine (presumed one uses detectChanges at the right places)

**Comment by Sirioxstar** [comment]
> Ciao, penso che siamo dalla stessa parte, quindi aggiungerò la mia domanda qui. Possiamo aggiungere una risorsa dello staff al calendario come immagine allegata? ![Screenshot_2019-11-14 Demo di animazioni angolari](https://user-images.githubusercontent.com/47124139/68897224-b89a4300-0735-11ea-8442-85a261866bfc.png)



> Hi, I think we are on the same side, so I will add my question here Can we add staff resource to the calendar as attachment image? ![Screenshot_2019-11-14 Angular Animations demo](https://user-images.githubusercontent.com/47124139/68897224-b89a4300-0735-11ea-8442-85a261866bfc.png)

hi,
were you able to implement this display mode?

**Comment by Sirioxstar** [comment]
@Kherat 
were you able to implement this display mode?

**Comment by EgoPlacebo** [comment]
I agree that cramming resources into one calendar's week view like that would be awkward, I had a requirement of showing multiple resources in a view, I achieved this by having a calendar per-resource using Angular's Component Factory. This works well  for not only weekly but also monthly views, and you can display many at once, side by side and/or stacked, depending on the space available.
![image](https://github.com/mattlewis92/angular-calendar/assets/7297852/dce82654-40d7-481c-9488-7349b0958f8b)

**Comment by mmadel** [comment]
Hi @EgoPlacebo . I have the same requirements like u regarding showing multiple resources on week view . I found your approach is great. But i am wondering what if we have to render more resources (in my case may be 10 to 15 resources) , Is this approach will fit. Did u tried with many resources . Thanks

**Comment by EgoPlacebo** [comment]
@mmadel hello, sorry I have not loaded it up with more than half a dozen resources at a time so I'm afraid I cannot help much. I didn't notice any significant performance issues with 6 displayed on one page, but the bookings present were not excessive in quantity either. It has been some time since I've touched that project.

Once the factory is set up though, it shouldn't be difficult to test!
