### ISSUE TITLE
exclude Hours

### ISSUE THREAD

**Issue by EliasKeller** [mattlewis92/angular-calendar#1174]
I want to exclude specific Hours on my Week-View. 

![image](https://user-images.githubusercontent.com/38786773/73919969-d99daa80-48c4-11ea-9aff-f26d0d1beb5c.png)

Is there a Way to do that?

**Comment by ALapaque** [comment]
@EliasKeller 
Hi you can certainly manage to do that and hide a segment thanks to a test which will check if you want to display this segment.
Try to do that by using a  [hourSegmentTemplate]="customHourSegmentTemplate"

https://mattlewis92.github.io/angular-calendar/#/custom-templates

**Comment by mattlewis92** [comment]
Hey there, unfortunately there's no built in way to do that as it's quite tricky to implement because it would break resizing and drag and drop. The way I recommend to do this is to add a disabled state to times you want to disable like this: https://stackblitz.com/edit/angular-7zsn3h?file=demo/component.ts Hope that helps! 😄

**Comment by dvdnhm** [comment]
if someone comes to this page via Google, check this URL:

https://mattlewis92.github.io/angular-calendar/#/day-view-start-end
