### ISSUE TITLE
Week View with Resource

### ISSUE THREAD

**Issue by ErditGold** [mattlewis92/angular-calendar#1181]
**Is your feature request related to a problem? Please describe**

Can the week view show resources like in the day view but something different, for example an input with dropdown names.

**Describe the solution you'd like**

Like in the day view, but with a dropdown on top of calendar maybe, to show resources names. When we click at a user i want to show their personal events.

**Describe your use case for implementing this feature**

I need to show more than one calendar at the time and the resources concept works wonderfully for that. It's great that the day-view has the ability to work that way and it would be greater if week-view did that too!

**Additional context**

Great work, Matt !

**Comment by ALapaque** [comment]
@ErditGold Hi there you can do as much as you want with custom template even in the header or the segment or the cell...

https://mattlewis92.github.io/angular-calendar/#/custom-templates

**Comment by mattlewis92** [comment]
I think to solve this you could put a `<select>` element above the calendar and then depending on what the user picks, you can filter the events that you pass to the calendar. Something a little like this, but instead of colors it would be the user's events that you want to display: https://stackblitz.com/edit/angular-7fcevg?file=demo/template.html Hope that helps! 😄
