### ISSUE TITLE
Work with UTC date

### ISSUE THREAD

**Issue by andy200486** [mattlewis92/angular-calendar#145]
Hi,

I received from the server date with this format : 

> 2017-02-01T08:30:00

If I do : 

`new Date("2017-02-01T08:30:00")`

I got this : 

> Wed Feb 01 2017 09:30:00 GMT+0100 (Romance Standard Time)

So in the calendar, in place that the activity begin on 08h30, it begin on 09h30.
I've trying to convert the date toIsoString(), but it seems that the calendar doesn't take it.

Do you have an idea to resolve that ?

Thanks a lot!

**Comment by mattlewis92** [comment]
It's because the date string has no timezone attached so it defaults to UTC. When you do new Date() in the browser it then automatically converts the date from UTC to your browsers timezone, hence the time difference. Maybe something like this can help you: http://sidewaysforward.com/2013/01/27/javascript-date-objects-userbrowser-timezones/
