### ISSUE TITLE
Improve performance of all components by using the onPush change detection strategy.

### ISSUE THREAD

**Issue by martijn19811** [mattlewis92/angular-calendar#1509]
**Is your feature request related to a problem? Please describe**

My feature is is related to performance issues, when using the HTML templates of the components in combination with other directives like a Bootstrap tooltip. I have noticed that change detection cycles are being run continuously. This definitely interferes with performance when using methods in HTML templates. Which is not recommended, I know, but sometimes unavoidable.

**Describe the solution you'd like**

Please make sure all Angular Calendar components use the onPush ChangeDetectionStrategy, as explained here: https://blog.angular-university.io/onpush-change-detection-how-it-works/. This will make sure cycles are only being run when an input of said component is reassigned or when an event inside the component has been triggered.

**Comment by martijn19811** [comment]
@mattlewis92  I donated through PayPal. Hoping you can spend some time on this.

**Comment by mattlewis92** [comment]
Hi there! Thanks for your donation, really appreciate it! All components are already compatible with `OnPush` change detection, if you enable it on the component in your app that uses the calendar then it enables it for all child components as well. If you take a look at the demo components, you can see that they all [have it enabled](https://github.com/mattlewis92/angular-calendar/blob/master/projects/demos/app/demo-modules/kitchen-sink/component.ts#L43). It's not on by default so that you can opt into it in your app, rather than forcing it to be always enabled. So tl;dr, all you should have to do is enable `OnPush` in your component that consumes the `mwl-*` components. 

If you're already doing that and still seeing unnecessary change detection cycles, please can you put together a minimal reproduction via stackblitz showing this (you can fork a starter from any of the demos by using the "Edit in stackblitz" button) and I'd be happy to debug further 😄

**Comment by martijn19811** [comment]
Oh lol thanks, I always thought (even after years working on Angular) you had to explicitly set the change detection strategy everywhere. Been reading up and you're absolutely correct. 

No need for me to setup something through stackblitz. You can close this request if you want to. You're doing a great job on this repo, keep those updates coming!

**Comment by mattlewis92** [comment]
> Oh lol thanks, I always thought (even after years working on Angular) you had to explicitly set the change detection strategy everywhere. Been reading up and you're absolutely correct.

It's not that well known at all, I've seen it trip up a lot of people when trying to enable it on the root component and suddenly the whole app breaks 😅  Glad everything is working well for you and thanks for the kind words! 😄
