### ISSUE TITLE
Can't import angular-calendar SASS files in an Angular project.

### ISSUE THREAD

**Issue by santam85** [mattlewis92/angular-calendar#1596]
**Describe the bug**

Can't import library SASS files in an Angular project. Getting the following error:
```
SassError: Can't find stylesheet to import.
   ╷
12 │ @import "~angular-calendar/scss/angular-calendar";
   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
  src/styles.scss 12:9  root stylesheet
```

**Minimal reproduction of the problem with instructions**

Create an empty Angular project that imports the SASS file in the app `styles.scss` by using:
```
@import "~angular-calendar/scss/angular-calendar";
```

**Versions**

- `@angular/core`: ^14.0.0
- `angular-calendar`: ^0.30.0

**Comment by dereekb** [comment]
This is good. I ended up running into this about a week or two ago and ended up copying over the sass stylings to my project . I [ended up modifying them](https://github.com/dereekb/dbx-components/blob/develop/packages/dbx-web/src/lib/extension/calendar/_calendar.scss) a bit more to fit the angular/material mixin style presented. 

The one thing I felt I needed to change was the fact that some of the styling classes are [defined at the top level](https://github.com/mattlewis92/angular-calendar/blob/3d4a22a80a379ed0f1971f6c62e33d0cf7c71b9c/projects/angular-calendar/src/modules/common/calendar-tooltip.scss#L32) instead of within a mixin.

You might want to consider enhancing the SASS files a bit more for customization later. I meant to make a feature request/offer about it. I'd also be opening to copying over a more compatible version of my changes eventually back to this library if that's something desirable. I think I ended up putting more angular material theming adjustments into it that may not all be necessary or need adjustments.
