### ISSUE TITLE
Material icons instead of font-awesome

### ISSUE THREAD

**Issue by mcdwight6** [mattlewis92/angular-calendar#200]
### Bug description / Feature request:
Using Material 2 in my application, so using the material icons makes more sense for me. I replaced the `label` property of the CalendarEventAction object with the `<md-icon>` tags for material like this:
    actions: CalendarEventAction[] = [{
    label: '<md-icon>add_circle</md-icon>',
    onClick: ({event}: {event: CalendarEvent}): void => {
      this.handleEvent('Edited', event);
    }
  }, {
    label: '<md-icon>clear</md-icon>',
    onClick: ({event}: {event: CalendarEvent}): void => {
      this.events = this.events.filter(iEvent => iEvent !== event);
      this.handleEvent('Deleted', event);
    }
  }];

The problem is that the material tags are stripped out by Angular as a security precaution because the `md-icon` tag isn't recognized as "safe" HTML. In the [Security Guide for Angular](https://angular.io/docs/ts/latest/guide/security.html#!#bypass-security-apis) it instructs to inject the `DomSanitizer` and call the `bypassSecurityTrustHtml` which returns a SafeHTML object, but a CalendarEventAction.label can only be a string. Is there a different way to do this that I'm missing?

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)

http://plnkr.co/edit/KfRH6n?p=preview

### Versions

Angular: @angular/core@4.1.0

Calendar library: angular-calendar@0.14.0

**Comment by mattlewis92** [comment]
It's not actually possible to use angular components this way as they need to be statically analysable for AoT. The workaround is to use the icon as a normal HTML element like so: http://plnkr.co/edit/uS9n5VCyGaskVf9utTP1?p=preview Hope that helps! 😄

**Comment by francisrod01** [comment]
Hi @mattlewis92 what's up?
I'm trying to style the calendar weekday using Material icons but it's a little bit complex.
Do you have a style guide for that?

Here's the time when we switch to material icons, instead of font-awesome:

![image](https://user-images.githubusercontent.com/4691768/103162274-48ca0900-47cd-11eb-99a9-92a68671b10c.png)


And now what I could style:

![image](https://user-images.githubusercontent.com/4691768/103162306-a8281900-47cd-11eb-8c6e-aeef032a954e.png)


If I try to change icons margin-top, that's what happens:

![image](https://user-images.githubusercontent.com/4691768/103162317-cf7ee600-47cd-11eb-9109-372eb4af7e03.png)

**Comment by mattmcardle** [comment]
@francisrod01 use `vertical-align: middle` rather than margin.
