### ISSUE TITLE
Unable to customize cursor on day cells.

### ISSUE THREAD

**Issue by ArnaudDenoyelle** [mattlewis92/angular-calendar#206]
### Bug description / Feature request:
Starting point : the "Min/Max date" example : https://mattlewis92.github.io/angular-calendar/#/min-max-date

I would like to be able to customize the cursor when a day's cell is hovered. For example : 

- "cursor:pointer" on valid days.
- "cursor:not-allowed" on invalid days.

Unfortunately, adding the CSS property"cursor: not-allowed" does not work. However, I can see in the developer tools that the corresponding HTML element has the value "not-allowed" for the property "cursor".

My guess is that it does not work because the day's HTML element is not a div but a non standard element mwl-calendar-month-cell

### Plunker
Plunker (I only added "cursor: not-allowed" in class "cal-disabled") : http://plnkr.co/edit/wibBG6hMkpv7F8KqP9d6?p=preview

### Versions

Angular: 4.0.0

Calendar library: ^0.14.0

Browser name and version: 
Chrome 58.0.3029.110 (64-bit)
Firefox 53.0 (64 bits)
Safari : 10.1 (12603.1.30.0.34)
On MacOS 10.12.4 (16E195)

**Comment by mattlewis92** [comment]
This happens because of the CSS rule `pointer-events: none;` which doesn't allow the mouse cursor to change. Removing it uses the disabled cursor, however this will allow the `dayClicked` output to run so you'll need to implement logic to check that the day clicked isn't disabled. Here's your plunker fixed: http://plnkr.co/edit/C4UCwix4icaXmcuMlZK7?p=preview
