### ISSUE TITLE
Add an event meta / data property to the `CalendarEvent` interface

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#218]
This is probably a nicer api than extending the CalendarEvent interface and prevents users accidentally polluting future possible event properties.

**Comment by etwillbefine** [comment]
I know its a hard breaking-change and maybe even not a better API but wouldn't it be better to make the calendar event (meta property) generic? When I extend the `CalendarEvent` interface I still have typings but using the new `meta` attribute makes it harder. So imo, the new API to prevent users accidentally polluting event properties is not worth losing typings?! :/

**Comment by mattlewis92** [comment]
Ohh good idea, I've not released this yet so it wouldn't be a breaking change

**Comment by mattlewis92** [comment]
That was easier than I expected 😄 https://github.com/mattlewis92/calendar-utils/commit/7821b04229302f6cfe074cf3c50865b2935a6cd7

**Comment by etwillbefine** [comment]
I did not know something like this is possible https://github.com/mattlewis92/calendar-utils/commit/7821b04229302f6cfe074cf3c50865b2935a6cd7#diff-fdb1138e6fb46aad8352fc0cbfb32a0eR49 
No BC, you're right :D (thought so because TS compiler will fail for generic classes without typing, but here comes the default awesome!)

**Comment by mattlewis92** [comment]
I didn't know it was possible, I just tried sticking it in and the compiler didn't complain 😛
