### ISSUE TITLE
Variable event height on week view

### ISSUE THREAD

**Issue by ElieSauveterre** [mattlewis92/angular-calendar#237]
### Bug description / Feature request: On the week view each row of events has a height of 33px. 
With a custom template I need to have more than 33px and the height should depend on the content of the event.

### For bugs only, a link to minimally working plunker that reproduces the issue (you can fork a starter from any of the demos)
http://plnkr.co/edit/vgBZceLkwXJkaxU5dYsh?p=preview

### Versions

Angular: 4.1.3

Calendar library: 0.17.0

Browser name and version: Chrome @ 59

**Comment by ElieSauveterre** [comment]
I think I have a solution.

I made a fix on my pull request #229 => [https://github.com/mattlewis92/angular-calendar/pull/229/commits/4ec860cf2cc5a4e5d6d138e6fcb361d7d447da9e](url)

**Comment by mattlewis92** [comment]
The events being positioned absolutely was intentional in order to fix this issue: https://github.com/mattlewis92/angular-calendar/issues/191 You can get the old behaviour back with the current API by overriding the CSS + forcing `absolutePositionedEvents`. Example plunker: http://plnkr.co/edit/fg9TgSDb4uauSI5tJiCg?p=preview Discussion here: https://github.com/mattlewis92/angular-calendar/commit/e6e02c5
