### ISSUE TITLE
Day view event alignment

### ISSUE THREAD

**Issue by andreroggeri** [mattlewis92/angular-calendar#260]
### Bug description / Feature request:
The events are misaligned with the time in the day view (See below)

![Issue](http://i.imgur.com/xf1XPT3.png)

[I made a repo since I couldn't reproduce the problem on plunkr](https://github.com/andreroggeri/angular-calendar-day-view-issue)

### Versions

Angular: 4.0.0

Calendar library:  0.18.1

Browser name and version: Chrome 58.0.3029.110 (64-bit) / Windows 10

**Comment by mattlewis92** [comment]
Ah it seems like the issue is because you're not using bootstrap, somewhere its document normalising ensures that each segment is 30px in height which is what the algorithm assumes is each segments height when positioning events. I've just released 0.18.2 with a hacky fix which should solve it for you. Hope that helps! 😄

**Comment by andreroggeri** [comment]
Ah, thats why I didn't noticed earlier. 

I just migrated from Bootstrap to Material. The new version worked like a charm !

Thanks for the blazing fast responde ! 😄

**Comment by mattlewis92** [comment]
Np, happy to help! 😀
