### ISSUE TITLE
Filtering events makes them not be draggable

### ISSUE THREAD

**Issue by sixsixtrample** [mattlewis92/angular-calendar#273]
## I'm submitting a ...

<pre>
[X] Bug report 
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
If `events` are filtered, or not defined outside of a function in the component, they lose the ability to be dragged.

### Minimal reproduction of the problem with instructions
In this Plunk I have a few arrays of events, and I try to filter those events based on the name of a user. The events display correctly, but they are no longer draggable. If I set the events equal to the array defined in the component, they display and are draggable. I've tried about 10000 permutations of this and I can't figure out why it doesn't work!

https://plnkr.co/edit/kes4oSbk5od0aQVWHqE8?p=preview

### Versions

Angular: 4.2.2

Calendar library: 0.19.0

Browser name and version: Chrome

**Comment by sixsixtrample** [comment]
Interestingly this does work:

http://plnkr.co/edit/3aqFrJKwePMakTqQEdpH?p=preview

But if you moved the creation of that array into another method and defined events as the return of that method, it would not.

**Comment by mattlewis92** [comment]
This is happening because you're calling the filter function on every cycle of change detection (by doing `[events]="filterEvents(events, 'John smith')"`), which re-renders the calendar when you try and drag the event and it loses its state that you're dragging it. You need to move the filter logic outside of the template and into the component for it to work like so: https://plnkr.co/edit/X9QFJEYLNtCmscRIcoHe?p=preview

**Comment by sixsixtrample** [comment]
Ah! I didn't realize events was tied to changeDetection. That makes sense!
