### ISSUE TITLE
Css Issue

### ISSUE THREAD

**Issue by jphearse** [mattlewis92/angular-calendar#306]
I have included node_modules/angular-calendar/dist/css/angular-calendar.css and still no luck.

This is the result I'm getting:

![calendar](https://user-images.githubusercontent.com/14226072/29141112-7cbe453e-7d12-11e7-80fb-9b3bb3483548.jpeg)

I noticed someone had the same issue [issue #77 ](https://github.com/mattlewis92/angular-calendar/issues/77). But I do not have a src/styles.css file. Any other ideas on how to fix the issue?

**Comment by jphearse** [comment]
![calendar1](https://user-images.githubusercontent.com/14226072/29173604-70fed046-7da9-11e7-8af7-78c011291014.jpeg)
I was able to get the styling working by adding this link to my index.html page
`<link href="https://unpkg.com/angular-calendar@0.20.0/dist/css/angular-calendar.css" rel="stylesheet">`

It would not work when I had this though: 
`<link href="/node_modules/angular-calendar/dist/css/angular-calendar.css" type="text/css" rel="stylesheet">`

Any ideas why?

**Comment by mattlewis92** [comment]
It's probably because your local dev server isn't serving the node_modules folder directly. Without knowing anything about your setup its impossible to really know more. There are examples for all common build tools here that might help you: https://github.com/mattlewis92/angular-calendar/tree/master/build-tool-examples
