### ISSUE TITLE
using angular-cli to make universal build causes the exception

### ISSUE THREAD

**Issue by wpcfan** [mattlewis92/angular-calendar#316]
I followed the https://github.com/angular/angular-cli/wiki/stories-universal-rendering , and but got the following exception, something related with `angular-draggable-droppable` dependency

```
> node ./index.js
/Users/wangpeng/workspace/ng/taskmgr/node_modules/angular-draggable-droppable/dist/esm/src/draggable.directive.js:1
(function (exports, require, module, __filename, __dirname) { import { Directive, ElementRef, Renderer2, Output, EventEmitter, Input, NgZone } from '@angular/core';
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.X37N (/Users/wangpeng/workspace/ng/taskmgr/dist-server/main.bundle.js:1:524039)
    at n (/Users/wangpeng/workspace/ng/taskmgr/dist-server/main.bundle.js:1:211)
```

**Comment by mattlewis92** [comment]
Looks like an issue with the tooling not transpiling the es6 modules, you probably want to raise an issue with the CLI + a repo that reproduces your issue and someone will be better able to help you there.

**Comment by wpcfan** [comment]
@mattlewis92 But you might want to take a look at https://github.com/angular/angular-cli/issues/7200 , it seems many third-party libraries not working with  angular cli's universal build, but they are trying to work with 3rd-party to make a solution. it seems your drag-drop package did not transpiled to commonjs. As angular-cli is very popular, so could you make it work with cli's universal build?

**Comment by mattlewis92** [comment]
The issue is that it is [already transpiled](https://npmcdn.com/angular-draggable-droppable@1.0.1) to commonjs - however the CLI is using the `module` entry point instead of `main` which points to the ES module format which doesn't work with node. The fix is for the CLI to configure webpack not to resolve the `module` entry point when building for universal. Removing the ESM module entry points would break tree shaking so that's not a viable option.

**Comment by mattlewis92** [comment]
Using this to run the built universal app is a good workaround in the meantime: https://medium.com/web-on-the-edge/es-modules-in-node-today-32cff914e4b

**Comment by wpcfan** [comment]
thanks a lot, I will take a look

**Comment by stephanegg** [comment]
@wpcfan @mattlewis92 could you please share some details on how to use @std/esm? With an example for this library for example? Many thanks

**Comment by stephanegg** [comment]
@mattlewis92 what do you think about the last comment in the angular cli 7200 issue (https://github.com/angular/angular-cli/issues/7200#issuecomment-329711848) ? Are you still convinced that you should not slightly change the build of your library ?

**Comment by mattlewis92** [comment]
Using a FESM still sounds like a hack to workaround something that should be fixed in the cli itself. The angular team are also [getting rid of FESM's in v5](https://github.com/angular/angular/pull/19190) as they don't work well with code splitting, plus adding rollup into the mix just adds a lot of extra complexity into the build system.
