### ISSUE TITLE
Need an example of how to do something

### ISSUE THREAD

**Issue by seigneur** [mattlewis92/angular-calendar#319]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Documentation issue or request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request
I am trying to create a week view along with time slots on the side see attached screen shot of full calendar.io example

![screen shot 2017-08-30 at 3 26 45 pm](https://user-images.githubusercontent.com/1625844/29860190-c3724954-8d97-11e7-9715-8fcea52e3183.png)

Currently, there is only an option to create a week view with no time on the side. Went through the documentation roughly, and did not get any ideas on how to implement this quickly with existing code. Is the best way to write a Custom Template for day view in this case?

### Versions

Angular: 

Calendar library: 

Browser name and version:

**Comment by mattlewis92** [comment]
The way I would go about this is to build a completely separate week view component and use it in place of the one this calendar provides, rather than trying to hack something into a custom template which will probably cause more trouble than its worth as the UX deviates too much. When building this lib I intentionally split out some of the more generic parts that could help you build this though. You could use the `calendar-utils` lib to [create the grid of times](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L581) and the [week days header](https://github.com/mattlewis92/calendar-utils/blob/master/src/calendar-utils.ts#L289). Then you could use [this](https://github.com/mattlewis92/angular-resizable-element) to make events resizable and [this](https://github.com/mattlewis92/angular-draggable-droppable) to make them droppable. The only complicated thing left for you to implement is the actual positioning of events on the grid. Hope that helps! 😄

**Comment by ankitjs** [comment]
@seigneur . Hi .. Were you able to solve this issue. I am still stuck in this one

**Comment by seigneur** [comment]
I used another library, but I think proceeding as suggested is a better
approach.
