### ISSUE TITLE
Pb with hour displaying (timezone issue) on week view calendar.

### ISSUE THREAD

**Issue by pjv03** [mattlewis92/angular-calendar#428]
Hi:) 
I have a pb with displaying hours on week view calendar on 29 of October on Paris/Europe timezone (for instance). I have event with start = Sun Oct 29 2017 08:00:00 GMT+0200 (EET) but on view it displayed as 9 AM (not 8). I think, it because on this day we have two timezone values GMT+0300 and after 4AM - GMT+0200 (EET). How to fix displaying? Thx.

**Comment by mattlewis92** [comment]
Please can you make a runnable repro on plunker / stackblitz etc that reproduces your problem, as it's pretty hard to work out what's going on without any code. Thanks! 😄

**Comment by pjv03** [comment]
Sorry, I can't add part of code to show pb, (project on sf3 + angular 4). 
Data for event get from symfony in format 
<img width="734" alt="2018-01-04 18 08 09" src="https://user-images.githubusercontent.com/23629322/34572535-4675a6de-f17a-11e7-8367-8217846a83d3.png">


then on component generated events 

<img width="536" alt="2018-01-04 18 05 31" src="https://user-images.githubusercontent.com/23629322/34572373-e89fdfe8-f179-11e7-9fbd-44268d3b36b3.png">

and we have data 
<img width="1196" alt="2018-01-04 18 09 17" src="https://user-images.githubusercontent.com/23629322/34572603-75060bba-f17a-11e7-9ca7-41f6bb43ee66.png">
<img width="1327" alt="2018-01-04 18 10 09" src="https://user-images.githubusercontent.com/23629322/34572636-8af46958-f17a-11e7-9d64-0f7c7edf410b.png">
<img width="1308" alt="2018-01-04 18 09 59" src="https://user-images.githubusercontent.com/23629322/34572637-8b348d1c-f17a-11e7-9f32-304d6abcbea2.png">

**Comment by mattlewis92** [comment]
I believe your issue is because your dates returned from your server don't have timezones encoded in them, thus UTC is assumed and they will automatically adjust to your local timezone. To mitigate this you should save all dates on your API with the timezone encoded in a format like ISO for example `2018-01-05T08:23:31.627Z`

**Comment by pjv03** [comment]
Ok, thx! I'll check

**Comment by sdstmi88** [comment]
Is it possible to use the week-view calendar completely independently of the client's time zone, that is, to use a specific time zone so that the start/end dayHour (00-23) refer to the local time of that defined time zone, not to the client's zone? 
Also I expect to get events mapped properly according to the specific time zone.
