### ISSUE TITLE
Pb with hour displaying (timezone issue) on week view calendar.

### ISSUE THREAD

**Issue by pjv03** [mattlewis92/angular-calendar#430]
Issue https://github.com/mattlewis92/angular-calendar/issues/428 still opened!

**Comment by mattlewis92** [comment]
I closed your original issue because it didn't follow the issue template which clearly stated `Please note that issues that ignore this template will be closed without notice!`. I maintain this repo in my own spare time for free, as a result I only have the capacity to help people that provide all the info needed to replicate an issue.
