### ISSUE TITLE
Multi-Day Event Can't be Dragged in Day View

### ISSUE THREAD

**Issue by eleventhaus** [mattlewis92/angular-calendar#436]
## I'm submitting a ...

<pre>
[x ] Bug report 
</pre>

### Bug description

In day view, unable to drag events in both directions if the event spans more than one day

### Minimal reproduction of the problem with instructions

[plunkr](https://plnkr.co/edit/wGa1bVC7BuqjE0rEpcqf?p=preview)

### Versions

Angular: v5

Calendar library: 0.23.2

Browser name and version: chrome

**Comment by mattlewis92** [comment]
This is by design as events can't be dragged outside of the view, but obviously it doesn't work great for events that span one day.  I've thought about this for a while for a nice UX that could solve this but I didn't come up with anything, the only thing I can think of is to make these events span the [whole day](https://mattlewis92.github.io/angular-calendar/#/all-day-events), it doesn't get you drag and drop but it is a slightly better UX for the user.

**Comment by satocw** [comment]
Hello! This is an excellent library, and I'm trying to use it in production, but this feature is required.

Can it be possible to enhance features so the events that span more than a day could be dragged?
I'm expecting a Google Calendar-like UI/UX.

That is, if you drag an event to another day, the length of the event decreases.
And if you drag and pull out an event from another day, the length of the event increases until the whole of the event appears in one day (then it can be dragged). 

Can you re-open this issue?
