### ISSUE TITLE
Multi-Day event drag&drop issue

### ISSUE THREAD

**Issue by volser** [mattlewis92/angular-calendar#443]
<pre>
[x] Bug report 
[x] Feature request
[ ] Support request
</pre>

### Bug description / Feature request
http://recordit.co/pWk8kjHxtr
When we have multi-day event and drag by not first day we have not correct newStart and newEnd.
I think need to use start drag day, or pass this info to drop event (to allow user shift dates)

And also will be cool to highlight multi days while drag

**Comment by mattlewis92** [comment]
This behaviour is by design, my thinking was to think of the event as one whole element, so regardless of which day you dragged it from, the new event start would always start from the day it was dropped on. I've exposed the day the event was dropped on so you can adjust the event start and end yourself - it is available on `$event.day.date` on the `eventTimesChanged` output for the month view. Hope that helps! 😄
