### ISSUE TITLE
Improved Day View Performance

### ISSUE THREAD

**Issue by developcodeza-matthew** [mattlewis92/angular-calendar#485]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Is it possible to remove unused listeners from each hour segment in the day view. Running a Chrome Profile shows me that there are well over 1000 DOM nodes with roughly 35 hour segments (17 hours with 15 min segments). 

Using Augury I notice that each CalendarDayViewHourSegmentComponent has a DroppableDirective. 

Is it possible to remove this if it is not being used?

And are there any other tips on improving performance in general?

### Versions

Angular: 5.2.3

Calendar library: 0.23.6

Browser name and version: Chrome 65

**Comment by mattlewis92** [comment]
Hi there, I put a great deal of care to make sure that there was no overhead of redundant event listeners in the draggable / resizable directives that would cause perf issues. Can you show me where exactly in the chrome dev tools you're seeing the perf issues reported from these directives? Thanks! 😄 

As for perf tips in general I've tried to do everything I can to make everything as performant as possible out of the box, I guess if you use ChangeDetectionStrategy.OnPush for all components that would help things.

**Comment by developcodeza-matthew** [comment]
Thanks @mattlewis92. Ill defiantly have a go at changing the ChangeDetectionStrategy. This is exactly where my issues is coming from. Angular material seems to be very trigger happy with the Change Detection especially when using modals / dialogs within the same component that holds the calendar.

I realise reading back that my question seems overly critical. My intentions were more along the lines of "Can I remove unused directives within the html with something like [mwlDragable] = 'false'" 

I've adapted the component to show 7 day view components side by side instead of the week view, as in my use case its important to display the event at the specific time slot. I know this is probably not what this was intended for but with tweaks if I can get it to work well this would be a near perfect solution.

This together with Angular Materials dialog CD Strategy is what I assume to be contributing to the slight slowdown.

**Comment by mattlewis92** [comment]
In order to remove the unused directives you would have to extend and override the templates of every single component that used the drag and drop directives (as angular cannot have dynamic component templates). However this probably wouldn't get you any major performance wins as the drag and drop event listeners are extremely lazy. If the calendar events are not set to `draggable: true` then the directives are effectively noop, if you take a look at the source you'll see what I mean: https://github.com/mattlewis92/angular-draggable-droppable/blob/master/src/draggable.directive.ts#L292 and even when events are draggable all event listeners run outside of the angular zone and don't trigger change detection cycles. I'm more than happy to debug more if you can provide some flame charts etc from the chrome dev tools that proof your perf issues are coming from this calendar. 

For more info have a look at this great article: https://blog.thoughtram.io/angular/2017/02/02/making-your-angular-app-fast.html 

Hope that helps! 😄
