### ISSUE TITLE
ExpressionChangedAfterItHasBeenCheckedError -  eventWidth?

### ISSUE THREAD

**Issue by joaolori** [mattlewis92/angular-calendar#491]
Hello,

I am facing this error:

ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'eventWidth: 59'. Current value: 'eventWidth: 60.0625'.

Its causing a lot of delay on calendar cause is firing this error like 100x times per event in calendar.
Anyone as faced this issue? Any solution?

Thanks in advance

**Comment by joaolori** [comment]
Is Week view and happens when mouve over event.

![image](https://user-images.githubusercontent.com/3897677/38497043-51c53656-3c1d-11e8-8640-ea7800ccd552.png)

**Comment by mattlewis92** [comment]
Ah I think I see what's happening here - the custom template that you are using to position the events on a week view with times is causing the problem. I guess the value you're passing to the `eventWidth` input is calculated by passing in the container elements `offsetWidth / 7`. I would recommend pre-calculating this once inside in your components controller (instead of in the template), and then manually updating it when the window is resized. That would stop it being updated on every change detection cycle and hopefully stop the error you're seeing. Hope that helps! 😄

**Comment by joaolori** [comment]
Hi Matt
I will check and get back to you. 
Thanks!

**Comment by rubenheymans** [comment]
any progress on this?
