### ISSUE TITLE
event template multiline in week view

### ISSUE THREAD

**Issue by amineparis** [mattlewis92/angular-calendar#493]
If we define multiline event template the next view overlaps with the first

**Comment by mattlewis92** [comment]
Please follow the issue template and attach a clear plunker etc that clearly reproduces the issue you're facing. Thanks! 😄

**Comment by amineparis** [comment]
the problem is that you are fixing event height in week view, if we have multiline event template it bugs

**Comment by mattlewis92** [comment]
The default demo auto truncates long event titles to handle this, if you've used a custom template I have no way of knowing what your issue is because you've written some custom code that I cannot see, hence why I asked for the plunker.
<img width="268" alt="screen shot 2018-04-06 at 13 27 53" src="https://user-images.githubusercontent.com/6425649/38418836-557a9e8e-399e-11e8-9e34-b344066864cb.png">

> people that use github may be working in companies and that are paied for time they spend in company interest and have things more important to do than creating plunkers for a problem that is easy to understund

Please bear in mind that I work on this project in my spare time for free. If your company is paying you to use other peoples free software, then you should spare a few minutes of your time to follow the guidelines when reporting issues on other peoples free software. I get dozens of issues opened across my projects, and I can only spare the time to answer those that provide specific reproductions of issues. If this isn't acceptable to you, then you are more than welcome to build your own calendar component that functions exactly how you would like it to.

If it's all the same to you, I would not like to engage with you further as this is a waste of energy on both sides. Best of luck with completing your project!  😄
