### ISSUE TITLE
Month View Alternates

### ISSUE THREAD

**Issue by mcb10** [mattlewis92/angular-calendar#499]
## I'm submitting a ...

<pre>
[ ] Bug report 
[x] Feature request
[ ] Support request => Please do not submit a support request here, please ask on https://stackoverflow.com/
</pre>

### Bug description / Feature request

Hello, I am exploring the ways to change the month view of the calendar so that the title of the events are always visible. Basically trying to replicate something similar to the calendar viewable on Mac/Macbook.
![month-vie](https://user-images.githubusercontent.com/38315618/38669250-c7c00cec-3e3d-11e8-8221-6f478024d3ad.png)
This is because when events carry over more than one day, I want to make it visually obvious on the month view of the calendar. 
I am relatively new to angular, but have a working version of your calendar on my machine. Please could you advise me whether there are any agreed features that could enable this styling. Or how you would go about this?
Thank you!

### Versions

Angular: 5

Calendar library: ?

Browser name and version: Google Chrome (v65)

**Comment by mattlewis92** [comment]
Hi there, I did investigate adding this UX before, but it ended up becoming way too difficult to implement so I stuck with the UX that you see today. The main problems are because the events need to be independently positioned from the calendar cells, so you end up in a mess where you are manually adjusting the height of the cells with JS depending on what events are present. The best visual queue you can give to the user that an event spans multiple days is the mouse over effect you get when you hover over an event. I'm really sorry that I couldn't be of more help 😞
