### ISSUE TITLE
Change viewDate and refresh.next() doesn't change CalendarMonthViewComponent

### ISSUE THREAD

**Issue by thorstenKoch** [mattlewis92/angular-calendar#544]
# Describe the bug
I want to change the current highlighted date initial set with **[viewDate]** in **CalendarMonthViewComponent**. The task is, that the click on any day in the month will change the focus to this day: Like clicking on the 29th of the previous month will change the month view to the previous month, highlighting the 29th day.

# Minimal reproduction of the problem with instructions
Therefore i took the event emitted from **(dayClicked)** and changed local viewDate attribute. Nothing happend.
Then i tried your refresh example: https://mattlewis92.github.io/angular-calendar/#/refreshing-the-view but nothing happend again.
How can i get CalendarMonthViewComponent to rerender with the new **[viewDate]**?

I found #216 and thought, this will be my workaround, but **[dayModifier]** isn't in the docs anymore.

# Versions (please complete the following information):
 - `@angular/core`: 5.2.0
 - `angular-calendar` = 0.24.x
 - Browser name and version: any

**Comment by mattlewis92** [comment]
Hey there, the solution in https://github.com/mattlewis92/angular-calendar/issues/216 should solve your problem, that API was updated a few versions ago which is why it doesn't work, you can see an example [here](https://mattlewis92.github.io/angular-calendar/#/before-view-render) for how to use the replacement API. Hope that helps! 😄
