### ISSUE TITLE
Show event start and end dates in UTC timezone

### ISSUE THREAD

**Issue by evilmonster18** [mattlewis92/angular-calendar#660]
**Is your feature request related to a problem? Please describe**

The start and end dates of my calendar events are always converted to my local timezone on the calendar. I know this happens because the dates are saved as Date() objects and the toString() method of that object is called to present the dates, but I wish there was another way around for this.

**Describe the solution you'd like**

The ability to change the date type of events or the method called to show the dates on the calendar. Being able to use moment() objects or call the toUTCString() method of native Javscript Date() objects.

**Describe your use case for implementing this feature**

Changing the timezone utilized in the presentation of events' start and end dates on the calendar.

**Additional context**

If this feature is already implemented, please inform me. I've browsed the entire library's documentation and cannot find a way to achieve this.

**Comment by mattlewis92** [comment]
In `0.26` you will be able to use moment instead of date-fns for all date manipulation. Instructions for how to install it are here: https://github.com/mattlewis92/angular-calendar/pull/589 

You'll need to use the `moment` adapter instead of `date-fns`, there's an example of how to do this [here](https://github.com/mattlewis92/angular-calendar/pull/589)

Please do let me know if that works for you, having some early feedback before I push this out to everyone will be great! 😄

**Comment by mattlewis92** [comment]
`0.26` is now released with this feature 🎉

**Comment by DerZyklop** [comment]
@mattlewis92 link is outdated. Here is the new one: https://github.com/mattlewis92/angular-calendar/tree/master/projects/demos/app/demo-modules/moment
