### ISSUE TITLE
RTL support for week view 

### ISSUE THREAD

**Issue by hope4555** [mattlewis92/angular-calendar#664]
**Is your feature request related to a problem? Please describe**

RTL support for week view would be great :)
See that events are pushed to the left

**Describe the solution you'd like**

```
 <mwl-calendar-week-view
       *ngSwitchCase="'week'"
      [viewDate]="viewDate"
      [events]="events"
      [refresh]="refresh"
      [locale]="locale"
      [ngStyle]="{'direction':currentLanguage==='he-IL' ? 'rtl' : 'ltr' }"
      (eventClicked)="weekEventClicked($event.event)"
      (dayHeaderClicked)="weekDayHeaderClicked($event)"      
      (eventTimesChanged)="eventTimesChanged($event)">
    </mwl-calendar-week-view>
```

**[ngStyle]="{'direction':currentLanguage==='he-IL' ? 'rtl' : 'ltr' }"**

**Describe your use case for implementing this feature**

Hebrew/Arabic support

**Additional context**

See image
![rtl](https://user-images.githubusercontent.com/5426569/43318939-84048ebc-91ab-11e8-9eb3-2e3a1880d279.png)

**Comment by mattlewis92** [comment]
Hi there, you can achieve this today by using a custom week view template and setting the `right` of events styling instead of `marginLeft`. I put together a demo of it working here: https://stackblitz.com/edit/angular-xn37qh?file=demo%2Fcustom-week-view.component.ts Hope that helps! 😄 

I've got a couple ideas on how to make this a bit more seamless in the next version though

**Comment by mattlewis92** [comment]
Dug into this today and the idea I had to make this a bit easier isn't feasible, so the best approach is to stick with the custom template for now.

**Comment by hope4555** [comment]
Thank you, this is working for me :)
