### ISSUE TITLE
[day view] allow dragging and dropping of all day events

### ISSUE THREAD

**Issue by mattlewis92** [mattlewis92/angular-calendar#665]
**Is your feature request related to a problem? Please describe**

A user should be able to drag and drop all day events on the day view as well

**Comment by blaz-rupnik** [comment]
is it possible to drag and drop event outside of box on day view? because I splited view so it contains sort of a grid, each column representing one user and I would like to drag and drop events from one user to another.

here is a screenshot:
![screenshot_2](https://user-images.githubusercontent.com/40405489/43458019-e77d229a-94c8-11e8-959f-cca56c97aae3.png)
