### ISSUE TITLE
Adding event to previous date and next date  

### ISSUE THREAD

**Issue by mustafa-synectiks** [mattlewis92/angular-calendar#690]
**Describe the bug**
Hi Mattlewis Im trying to add events on other dates except active date and i tried but its not working I added add event button out side calendar it is adding event to current date,  as i want to add event for other dates like next day or the other day. 
Thank you.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
The position of events is controlled by the `start` and `end` properties, it sounds like you're setting the `start` property to the current date rather than a different date. You can see the demo for how this works: https://github.com/mattlewis92/angular-calendar/blob/master/demos/demo-modules/kitchen-sink/component.ts#L78-L79 Hope that helps! 😄
