### ISSUE TITLE
Cannot extend CalendarMonthCellComponent

### ISSUE THREAD

**Issue by AhHa45** [mattlewis92/angular-calendar#738]
**Describe the bug**

Extending CalendarMonthCellComponent is not possible.
I was able to extend CalendarMonthViewComponent and also CalendarWeekViewComponent but not CalendarMonthCellComponent.

( "Unknown Input properties (...) if it's a angular component make sure its part of a ngModule...(...)")

I see that when I import e.g.  the CalendarMonthViewComponent it's imported from "angular-calendar" whereas CalendarMonthCellComponent is imported from "angular-calendar/modules/month/calendar-month-cell.component" as angular-calendar has no exported member CalendarMonthCellComponent.

I would like to add a more events panel to my month cell so that when the events per day are exceeding 2 events the user can click a button in the bottom of the cell to show more events in a absolute positioned panel.

**Minimal reproduction of the problem with instructions**

[stackblitz](https://stackblitz.com/edit/angular-zpkvcd-qyzask?file=demo%2Fmy-calendar-month-cell%2Fmy-calendar-month-cell.component.ts)

**Screenshots**

**Versions**

- `@angular/core`: 6.0.0
- `angular-calendar`: 0.26.0
- Browser name and version: Chrome Version 69.0.3497.92

**Comment by mattlewis92** [comment]
For the internal components i.e. not the root month / week / day components, these are designed to be extended by using templates as it's a slightly better developer experience rather than having to extend loads of components. If you have a look at the [readme](https://github.com/mattlewis92/angular-calendar#how-do-i-use-a-custom-template), it gives an example of how to do what you want. Hope that makes sense 😄

**Comment by AhHa45** [comment]
thx, I got it working without extending the component 👍

**Comment by ayaka209** [comment]
it's possible before 0.26.0.. now I have to use template..
