### ISSUE TITLE
Tooltips are gone after a dialog was open

### ISSUE THREAD

**Issue by papaiatis** [mattlewis92/angular-calendar#829]
**Describe the bug**
Tooltips won't show after a dialog was open.

**Minimal reproduction of the problem with instructions**

1. Go to https://mattlewis92.github.io/angular-calendar/#/kitchen-sink
2. Switch to Week view
3. Move the mouse over the events to see their title in tooltip (both regular events and all day event)
4. Click on any of the event so that a dialog appears (Event action occured)
5. Close the dialog
6. Try step #3 again: you will see that the tooltips are missing from the regular events, but not from the all day event

**Versions**

Latest version, can be reproducible on the demo site

- `@angular/core`: 7+
- `angular-calendar`: latest
- Browser name and version: Chrome latest, Firefox latest

**Comment by G3nius** [comment]
This happens because dragStarted sets dragActive to true, which cancels the tooltip, but dragEnded is never called to set it back to false, since it was never really dragged.

Is there a reason not to use (dragStart) instead of (dragPointerDown)? It will fix it, but I'm not sure why fd30c39529d14ca88b6be39a160913da6b284218 changed it in the first place.

**Comment by ryrobbo** [comment]
I can also confirm this behaviour in Angular 7.

I am also using the Material Dialog modal instead of the Bootstrap modal. After dismissing the modal dialog, the tooltips for the events no longer show.

**Comment by papaiatis** [comment]
@mattlewis92 looks like @G3nius has a good approach to fix this issue. Can you please confirm if that would work for you as well?
For me this looks like a low hanging fruit (bug).

**Comment by mattlewis92** [comment]
There definitely was a reason for using `dragPointerDown` instead of `dragStart` but I can't remember what it was, and changing it does seem to fix the issue. I've just released `0.26.11` with the change, please let me know if that works for you, thanks @G3nius for pointing me in the right direction! 😄
