### ISSUE TITLE
Events not displaying in IPad devices

### ISSUE THREAD

**Issue by naveenatti** [mattlewis92/angular-calendar#843]
@mattlewis92 
when i am trying load angular calendar with custom templates in angular 5 application its not rendering the events in Ipad pro Devices remaining devices its working as expected. please help on this.

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by mattlewis92** [comment]
Please follow the issue template and re-open a new issue with a minimal stackblitz or something similar that reproduces your code, without this it's impossible to comment further on what the issue might be. Thank you! 😄

**Comment by obraeckman** [comment]
@mattlewis92 @naveenatti 
I'm also reproducing this on an iPad Pro.

What is strange though is that it seems to be due to my application because it works fine when I open the kitchen sink demo site on the iPad.

Difficult to tell since I have no chrome console or any debut tool on the ipad... 
The calendar renders absolutely fine... it's just the events that are not displayed for some reason...

I know it's not much ... but any help would be greatly appreciated!

Kr,
Olivier

**Comment by obraeckman** [comment]
@naveenatti @mattlewis92 
I found the reason... 
It has nothing to do with the calendar.
This was due to a difference in Chrome vs Safari to handle the dates received from my backend
For some reason, Safari is unable to recognize dates in format dd-mm-yyyyTHH:mm:ss.00000

Once I had converted to something it recognises, my events are now correctly showing up!

Kr
Olivier

**Comment by suvish30** [comment]
Hey, 
I made a project in angular using this angular calendar. Issue is that I can perfectly see my event on web browser and adroid browser, but events are plotted differently when I see this component from iPhone chrome browser. In iPhone chrome some days I see more events some days I see less events
then the actual events.
