### ISSUE TITLE
Week view doesn't render properly when dayEndHour=24

### ISSUE THREAD

**Issue by JorgeSolFerreira** [mattlewis92/angular-calendar#907]
**Describe the bug**

When setting the dayEndHour property of the calendar week view  to 24, events that start at the beginning of the day don't render properly.

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-b6tryr

**Versions**

- `@angular/core`: 7.2.7
- `angular-calendar`: 0.26.6
- Browser name and version: Chrome 72.0.3626.119

**Comment by JorgeSolFerreira** [comment]
When the dayEndHour > 23 or the dayStartHour < 0 the events render to the next or the previous day. If this isn't an intended behaviour the calendar should limit the day hour range.

**Comment by mattlewis92** [comment]
It is [mentioned in the docs](https://mattlewis92.github.io/angular-calendar/docs/components/CalendarWeekViewComponent.html#dayStartHour) that the value must be 0-23 (as 24:00 is 00:00 the next day). I guess instead of failing weirdly, I can change the behaviour to do `Math.max(Math.min(23, dayStartHour), 0)` which would probably help avoid errors like this.
