### ISSUE TITLE
Make it responsive?

### ISSUE THREAD

**Issue by gaurav517** [mattlewis92/angular-calendar#92]
The calendar is awesome. Next step would be to make it responsive? I can't add the tag for enhancement.. but I think it would be pretty good if the month/week views are responsive.

**Comment by mattlewis92** [comment]
Unfortunately I have no design / UX skills, I borrowed the original design from [here](https://github.com/Serhioromano/bootstrap-calendar). I think due to the nature of the calendar itself it would be pretty much impossible to just solve this via CSS and it would probably require a completely separate template for each view.

**Comment by fzs1994** [comment]
How about just give a horizontal scroll?
