### ISSUE TITLE
Hijri calendar support

### ISSUE THREAD

**Issue by HKTemp** [mattlewis92/angular-calendar#924]
**Is your feature request related to a problem? Please describe**

Hello, I've looked at the demos and documentation, but I couldn't find if you support the Islamic Hijri calendar? From what I've seen it looks like it is not supported?

**Describe the solution you'd like**

Support for the Islamic Hijri calendar.

**Describe your use case for implementing this feature**

Support for the Islamic Hijri calendar is a requirement for me because I have customers that use this calendar.

**Additional context**

**Comment by mattlewis92** [comment]
There isn't any support for this out the box, _but_ you can provide your own date adapter to add this. There's an example of how to do this for the Jalali calendar [here](https://github.com/mattlewis92/angular-calendar/issues/779#issuecomment-433612309). You can use [this package](https://www.npmjs.com/package/moment-hijri) instead of `moment-jalaali` and it should give you the functionality you need. Any problems, give me a shout! 😄

**Comment by devfadl** [comment]
you can view the hijri adapter from my repo:

https://github.com/devfadl/angular-hijri-calendar/tree/main/src/app

**Comment by MohammedAldosari** [comment]
I've developed Hijri adapter that seamlessly integrates both the Hijri and Gregorian calendars, offering a comprehensive solution for diverse calendrical needs.

[Hijri-Angular-Calendar](https://github.com/MohammedAldosari/hijri-angular-calendar#hijri-angular-calendar)
