### ISSUE TITLE
3AM in Week View and Day View is missing

### ISSUE THREAD

**Issue by romanbondarev** [mattlewis92/angular-calendar#936]
**Describe the bug**
On the week and day view when all hours are viewed (12AM-11PM) the 3AM is missing in the left column.

**Minimal reproduction of the problem with instructions**
All Angular 6.0+ demos except recurring events, exclude weekends and use moment.
Although when running "use moment" from stackblitz, 3AM disappears.

**Screenshots**
![image](https://user-images.githubusercontent.com/32781374/55289858-9afdb080-53d4-11e9-83b9-cb5a1a242975.png)
From Stackblitz "Use moment" demo
![image](https://user-images.githubusercontent.com/32781374/55289880-cb454f00-53d4-11e9-91ab-7d0f98c0818b.png)

**Versions**

- `@angular/core`: 7.2.10
- `angular-calendar`: 0.27.1
- Browser name and version: Chrome Version 73.0.3683.86

**Comment by mattlewis92** [comment]
So this is a known issue with date-fns (It doesn't support UTC mode so all date calculations are done in your browsers local time). I'm guessing you're in a timezone that just moved to daylight savings, so technically that hour doesn't exist and the clock just moved forward one hour. Obviously this isn't a great UX to the user though, so the only solution is to use moment instead of date-fns and force the calendar to operate in UTC mode. There's an example of how to do this here: https://github.com/mattlewis92/angular-calendar/issues/477#issuecomment-418202991 Hope that helps! 😄
