### ISSUE TITLE
Week view is slow

### ISSUE THREAD

**Issue by sylvain-fr** [mattlewis92/angular-calendar#942]
The week view is slow. 

Even on online demo the week view is much slower than the month view. It takes 1 or 2 seconds to change week. On my environment it takes one more second.
Is there a way to improve it ?

**Versions**

- `@angular/core`:Current online version
- `angular-calendar`:Current online version
- Browser name and version: chrome 73

**Comment by mattlewis92** [comment]
I noticed that too (https://github.com/mattlewis92/angular-calendar/issues/922) and found the culprit to be hammerjs, adding all the tap handlers for each segment of the week view turned out to have quite a perf hit. Are you using hammerjs by any chance? Also do you use the `hourSegmentClicked` output? I can probably disable adding the tap events if the `hourSegmentClicked` isn't set, and maybe even lazily initialise the listener using requestIdleCallback which should take care of the worst of the performance issues which are causing that initial render lag.

**Comment by mattlewis92** [comment]
I just released `0.27.3` which makes things a lot faster now, on the demo the initial render of the week view is <200ms 🎉 Everything else in the profiler was just DOM elements rendering, so maybe when ivy is stable this will get even faster 😄
