### ISSUE TITLE
Events can Hang off Bottom of Week View in Same Week as DST Start

### ISSUE THREAD

**Issue by JaxonWright** [mattlewis92/angular-calendar#964]
**Describe the bug**

When you are in Week View and the week includes the day that Daylight Savings Time starts (2nd Sunday of March), 2 AM is skipped in the labels. This causes events that span midnight on the following days to hang off of the bottom of the view.

**Minimal reproduction of the problem with instructions**

Use this set of events and look at the week view starting on March 10, 2019:

````javascript  
events: CalendarEvent[] = [
    {
      start: new Date(2019,2,10,1),
      end: new Date(2019,2,10,3),
      title: 'On DST. I\'m fine',
      color: colors.red,
    },
    {
      start: new Date(2019,2,11,23),
      end: new Date(2019,2,12,9),
      title: 'I am hanging off!',
      color: colors.yellow,
    },
    {
      start: new Date(2019,2,12,21),
      end: new Date(2019,2,13,9),
      title: 'I am also hanging off!',
      color: colors.yellow,
    },
    {
      start: new Date(2019,2,13,21),
      end: new Date(2019,2,13,24),
      title: 'I hang off weirdly!',
      color: colors.yellow,
    }
  ];
````

https://stackblitz.com/edit/angular-gequfa

**Screenshots**

https://i.imgur.com/WhW67tW.png

**Versions**

- `@angular/core`: 7.2.14
- `angular-calendar`: 0.27.7
- Browser name and version: Chrome 74.0.3729.108

**Comment by mattlewis92** [comment]
So there's actually 2 issues here:

1/ The events shouldn't hang off like that on the week view, so weird that they don't on the day view though, as it's all the same code 🤔 Will try and find a fix for that. In the mean time you can force the view date to be in UTC like this to work around it: `viewDate: Date = new Date(Date.UTC(2019,2,10,1));`

2/ The last `'I hang off weirdly!',` event appears wrong because you're setting the hour to `24` in `new Date(2019,2,13,24)`. `24:00` is actually `00:00` the next day, which is why you see that slight 1px on the next day because it is correctly showing that the event ends at midnight that day. Instead you can set the date to be `23:59` by doing `end: new Date(2019,2,13,23,59),` which will solve the issue

Here's your demo fixed: https://stackblitz.com/edit/angular-gequfa-n8qh11?file=demo/component.ts 

Hope that helps! 😄

**Comment by mattlewis92** [comment]
Had another look at this today with fresh eyes, and realised the main reason for this happening was because the `viewDate` is on a day with daylight savings so it messes things up by only having 23 hours in the day. Unfortunately there's not a lot I can do out of the box to solve this so the workarounds I can suggest are:

1/ Make sure the view date is never a day with DST (as mentioned above, `new Date(Date.UTC(2019,2,10,1));` works because it essentially sets the view date to the day before DST occurs)

2/ Use moment and make the calendar operate in UTC: https://stackblitz.com/edit/angular-tfpxcn?file=demo%2Fmodule.ts Sadly date-fns doesn't yet support UTC mode so you have to use moment for this for now. You'd also need to make some adjustments in your app to handle all dates now being in UTC.

Hope that helps! 😄

**Comment by JaxonWright** [comment]
> 2/ The last 'I hang off weirdly!', event appears wrong because you're setting the hour to 24 in new Date(2019,2,13,24). 24:00 is actually 00:00 the next day

Ah that makes total sense.

As for a fix that doesn't require being in UTC, is it at all possible to just have the intervals on the _week_ view to include 2am even on this week? That would solve the problem, I am just not sure how feasible it is.

**Comment by mattlewis92** [comment]
> As for a fix that doesn't require being in UTC, is it at all possible to just have the intervals on the week view to include 2am even on this week? That would solve the problem, I am just not sure how feasible it is.

I've looked into that before and it's not possible as date-fns doesn't support UTC mode and only operates in the browsers local timezone, so 2am on that date literally doesn't exist (if you add 1 hour to 1am on that date you get 3am), so even if I added a duplicate for 1am, then 1am would appear twice as you can't format it to make it appear as 2am. The only real way to fix it is by making everything operate in UTC mode via moment as DST doesn't exist in that timezone.

**Comment by mattlewis92** [comment]
Please give `0.27.18` a go, it should fix this problem out the box now 🎉

**Comment by JaxonWright** [comment]
Oh, cool!
