### ISSUE TITLE
Become a sponsor on Patreon to ask questions but only silver level or higher!!?

### ISSUE THREAD

**Issue by jcanning** [mattlewis92/angular-calendar#968]
To ask any questions you'd like about the calendar beyond bug and feature requests, you must become a silver sponsor or higher on Patreon: https://www.patreon.com/mattlewis92

Hey Matt, 

I am all for you making money off this project, i really think it is great but I feel like forcing people to spend $250 American for just a question is a bit steep. Is there any other way that someone can ask a question other than doing this?

Why not sell the product as a whole rather than doing it for free and limited folks for questions? I feel the issue i have is pretty simple but it is not $250 ($335.94 CAD) worth to ask and now has me looking elsewhere for another product simply because I can no longer ask questions.

Or sell support packages for certain levels. Like $10 a question (something reasonable for your time)?

Anyways, this is pretty disappointing choice for such a great product.

**Comment by mattlewis92** [comment]
Hey John,

Sorry to hear that you're frustrated with what I'm currently offering. Let me explain a bit behind the motivations for the pricing. 

First off, I've never allowed support issues on this repo, I've always [redirected people to stackoverflow](https://github.com/mattlewis92/angular-calendar/blob/65d354b6817d9fdc105f2a796156c9ff7dd5dfa1/.github/ISSUE_TEMPLATE.md) where there would be someone else that can provide an answer. I've worked on open source nearly every day for the past 4 years, all in my free time simply because I enjoyed it, and never earned a penny from it, other than by using it as a lead generator for contracting work. I used to provide free support as well on the issue trackers for my repos but it got overwhelming and I got a bit burnt out so I had to just shut off everything that wasn't a feature or bug request as a way of handling it, which really wasn't great because then no one had a way of getting support.

Hence forth I decided to try and find a middle ground this year of trying to make the project financially stable. The first thing I indeed looked at was offering a commercial licence, the issue with that is that the project is currently licensed under MIT and several other people have contributed to the project, so I would need the express consent of every past contributor in order to re-licence it. Plus I really don't support the idea of giving something for free and then ripping it away from people and making them pay. When someone is used to having something for free and you take it away then it just causes too much friction. If I was starting from scratch then I would just offer a commercial licence from day 1.

So the pricing model I settled on was keep it free and offer a support licence. Rather than offering a years agreement for a steep price per year, I thought a SaaS style monthly option seemed fairer. My hourly contracting rate is $100 an hour, so $250 seemed fair to dedicate ~2.5 hours a month per person that subscribes to the plan. But this is mainly aimed at big companies where that kind of cash is negligible to them, I agree it certainly doesn't work for everyone including yourself. If you can point me to a platform that exists today that would facilitate the $x per issue style of payment, I would be very happy to signup and start using it, but AFAIK nothing like this exists today. Also as you are already donating money to the project, if you [email me](http://scr.im/mattlewis92) occasionally with a question, I'm certainly not going to turn you away and would be happy to help you with any questions. 

I hope that makes sense, please reach out to me if you'd like to discuss it more ✌️

**Comment by jcanning** [comment]
Hey Matt. Thanks for explaining that. It makes a lot more sense. Your bot makes it feel like you cant ask a question without being silver sponsor, that is why i posted that. Also did not realize folks were using stackoverflow for questions so that will be helpful as well. Appreciate you responding to this!

**Comment by mattlewis92** [comment]
Yeah there's definitely some room for improvement there, the idea I'm toying with right now is to allow support questions, then the bot will auto reply with a payment link to stripe, you can hit that and then send over $10 or something per issue. It would also allow x questions a month for free for people already donating on Patreon.
