### ISSUE TITLE
hourSegmentClicked  with more than just date

### ISSUE THREAD

**Issue by SenCodeMaker** [mattlewis92/angular-calendar#971]
**Is your feature request related to a problem? Please describe**

First thank you for the good job you have done here. I don't know how much of your time you are offering with this library but it is of great help. May God bless you for that in the name of Jesus.

My question is about the hourSegmentClicked function. I don't see why the event sent only contain the date of the segment. As we can see in the demos one then need to go through all the day hours and all the segments to find the selected one by comparing date times and do the work like put a css class or something.

**Describe the solution you'd like**
Why don't just send a thing to identify the segment or maybe the segment itself ? Because this information is already known at click time and we go around to look for it back which is inefficient.

**Describe your use case for implementing this feature**

Another feature request : As big part of the job consist in puting selected class to the element why not having and ng-if tied to a property selected which can be set true/false in the component.ts ? So the user can control selection/deselection easily in the controller with an array of boolean refereing to each segment or day ? For this second one it's just an idea don't bother to much.

bye bye.

**Comment by mattlewis92** [comment]
Hey, thanks for opening an issue. The main reason for only the date being exposed is mainly for historical reasons, before the `cssClass` was a thing, so the only thing to expose was the date. But I'm not sure exposing the segment to add the cssClass would help you, as it would be a buggy implementation. If you switched the date so the view got re-rendered or added or removed an event, then the date would be unselected, as the `segments` exposed only exist for that single render of the view. This is why the selectable period demo uses the `beforeDayViewRender` output to re-add the selected class on subsequent renders, so you're guaranteed that the `cssClass` will always be added.

The reason for not baking this feature directly into the calendar is because there are so many users of this library (`25,000+` a week right now), if I added every feature that anyone requested the library would be bloated with too many features, instead it's better to give low level APIs and allow you to build the functionality you need specifically for your app on top. For example if I added this directly into the calendar then someone would come along who would only want one day at a time selected, someone else might only allow you to select times within a certain range etc. As you can see the API would then grow to have to support all these use cases, instead by letting you implement it yourself, then you can handle all the specific use cases yourself without anything having to change in the calendar itself.

I hope that makes sense! 😄
