### ISSUE TITLE
Exclude Week days doesn't work in the week view with 6 days excluded

### ISSUE THREAD

**Issue by suelaine** [mattlewis92/angular-calendar#978]
**Describe the bug**

Is it possible to show only one day of the week? 

When I use the exclude days property excluding six days (ex: excludeDays: number[] = [1,2,3,4,5,6];)  on (https://stackblitz.com/run?file=demo/component.ts) 
I get the following errors on the week view:

ERROR
Error: Cannot read property 'date' of undefined
and
ERROR
Error: Cannot read property 'allDayEventRows' of undefined

could you help me, please?

**Minimal reproduction of the problem with instructions**

https://stackblitz.com/edit/angular-r5ehut?file=demo/component.ts

**Screenshots**

**Versions**

- `@angular/core`: ^6.1.8"
- `angular-calendar`:Angular 6.0+ calendar
- Browser name and version: Google Chrome

**Comment by mattlewis92** [comment]
I think the issue you're having is because the viewDate is set to `new Date('2016-01-05')` which is a monday which you're excluding, I would recommend instead setting `[daysInWeek]="1"` on the week view which will give you the behaviour you're after: https://stackblitz.com/edit/angular-r5ehut-zzsigg?file=demo/component.ts Hope that helps! 😄
