### ISSUE TITLE
Double click event 

### ISSUE THREAD

**Issue by vicky-rain** [mattlewis92/angular-calendar#991]
**Describe the bug**

**Minimal reproduction of the problem with instructions**

**Screenshots**

**Versions**

- `@angular/core`:
- `angular-calendar`:
- Browser name and version:

**Comment by vicky-rain** [comment]
I want to add a double-click event to the event of "dayClicked". What can I do?

**Comment by vicky-rain** [comment]
I use custom events, but blank dates on the calendar don't work.

**Comment by mattlewis92** [comment]
You can use a custom template to do this, you can see an example of how to do it here: https://stackblitz.com/edit/angular-2gnxfv?file=demo/component.ts Hope that helps! 😄

**Comment by hitallow** [comment]
this isn't a good way to solve this problem, i have to override all template for only add a new event.

**Comment by sai0553** [comment]
currently hourSegmentClick works with a single click on the calendar view, but my requirement is that I should open a popup with double click. I tried to use (dblClick) event, but it sends me MouseClick event. I am struggling to get the time on which the user clicked the calendar. hourSegmentClick $event is perfect one, but want to fire the same event on double click. I tried to understand your stackblitz but may be due to my lack of experience, I was unable to figure it out. Any help would be appreciated.

**Comment by timyshark** [comment]
it is great solution, thanks Matt, great job!

**Comment by umdstu** [comment]
Just wanted to share what I believe to be a much better way of enabling this behavior. The trick is to debounce the single-click event.

`component.html`
```
<mwl-calendar-day-view (eventClicked)="mimicDblClick($event)"></mwl-calendar-day-view>
```

`component.ts`
```
private eventClicked = new Subject<string>();

ngOnInit() {
    const eventClickedDebounce = this.eventClicked.pipe(debounceTime(200));
    eventClickedDebounce.subscribe((event: any) => {
      // trigger whatever you wanted the double click to do here
    });
}
  
mimicDblClick(event: any) {
  this.eventClicked.next(event.event);
}
```
